### ISSUE TITLE
Updating a team in the Admin Web UI breaks short name

### ISSUE THREAD

**Issue by kevinreedy** [kevinreedy/shuffio#109]
If you edit a team in /admin and leave the short_name blank, it saves "" to the database rather than nil

**Comment by mdmccoy** [comment]
It's hacktoberfest again and this looks like it's a bug from something that I added soooooo maybe I'll try to fix it?

**Comment by mdmccoy** [comment]
I'll probably just overload the setter so that, if the short name is blank, it saves nil instead.
