### ISSUE TITLE
8-frame playoff group play matches should count less

### ISSUE THREAD

**Issue by aaronpolitsky** [kevinreedy/shuffio#165]
create awareness that it is an 8-frame match. 
use this signal to modify k-factor in ELO.

**Comment by kevinreedy** [comment]
Things you'll need to do:
 - [ ] Create a migration on the Match object to add a floating point field called "multiplier", default 1.0
 - [ ] Update app/models/match.rb's `calculate_elo` method to use the multiplier on the k-factor
 - [ ] Make a rake task to update the multiplier on any match with a comment that matches `Group Play` to 0.5, and call Match.recalculate_all_elo

**Comment by kevinreedy** [comment]
Fixed by https://github.com/kevinreedy/shuffio/pull/167
