### ISSUE TITLE
Add toggle to /teams for current teams

### ISSUE THREAD

**Issue by kevinreedy** [kevinreedy/shuffio#28]
Right now /teams shows all teams. We should have a toggle to show only teams in the current season as well.

**Comment by mdmccoy** [comment]
@kevinreedy how were you thinking about doing this? Super easy would be just adding a link to a differnt view, or did you want to go the JSON route?

**Comment by kevinreedy** [comment]
probably just a get param that the controller uses to toggle its search, and then have the view have a toggle back and forth

**Comment by mdmccoy** [comment]
Haha, yea, that makes sense. I've been working on a big complicated app for
so long I'm a little rusty on how to do the simple things.

**Comment by kevinreedy** [comment]
All good! I didn't really detail these out too well, so it's great that you are asking questions!
