### ISSUE TITLE
Add short_name to Team

### ISSUE THREAD

**Issue by kevinreedy** [kevinreedy/shuffio#34]
Some teams have a long name that is getting cut off. Add short_name to Team and use it if exists on rank boards.

**Comment by kevinreedy** [comment]
@mdmccoy I think we can move the complexity to the user. Let's just add this field, and not worry about how to populate it. Then we can have a method that returns `short_name ? short_name : long_name`, and update views to use it.

**Comment by mdmccoy** [comment]
Ah, so, if the team doesn't like that their name is being cut off, they could add a `short_name` ?

**Comment by kevinreedy** [comment]
yep! except it'd be more "they can bug kevin to add a short_name to the db" for now :P

**Comment by mdmccoy** [comment]
Hahaha, right on. I didn't know if you were chill with additional administrative overhead.
